### ISSUE TITLE
run TermiusTools failed

### ISSUE THREAD

**Issue by Jonson-zhang** [ZEERDEER/Termius-Crack#5]
when I run TermiusTool.exe , it show error like this 

C:\Users\cdpf\AppData\Local\Programs\Termius>TermiusTool.exe
Node.js is required. Install? (y/n): y
Downloading Node.js...
[==================================================] 100.0%
Installing Node.js, please wait...
Node.js installation failed: Command '['msiexec.exe', '/i', 'C:\\Users\\cdpf\\AppData\\Local\\Temp\\nodejs_installer.msi', '/quiet', '/norestart']' returned non-zero exit status 1603.
Node.js not installed, exiting

**Comment by ZEERDEER** [comment]
Try running as an administrator or manually install [node.js](https://nodejs.org/).
